<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Title>ImageMagitek.Plugins.Contracts</Title>
    <RootNamespace>ImageMagitek.Plugins</RootNamespace>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <RepositoryUrl>https://github.com/stevemonaco/ImageMagitek</RepositoryUrl>
    <PackageProjectUrl>https://github.com/stevemonaco/ImageMagitek</PackageProjectUrl>
    <IsTrimmable>true</IsTrimmable>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <EnablePackageValidation>true</EnablePackageValidation>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>
