<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<PropertyGroup>
		<VersionPrefix>0.993</VersionPrefix>
		<VersionSuffix>preview</VersionSuffix>
		<Authors>Stephen Monaco</Authors>
		<Company>Stephen Monaco</Company>
		<Copyright>Copyright © Stephen Monaco 2024</Copyright>
	</PropertyGroup>
	<PropertyGroup>
		<AnalysisLevel>latest</AnalysisLevel>
		<LangVersion>latest</LangVersion>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<PropertyGroup Label="Avalonia licensing">
		<_AvaloniaLicenseKey>$(AvaloniaUILicenseKey)</_AvaloniaLicenseKey>
		<_AvaloniaLicenseKey Condition="'$(_AvaloniaLicenseKey)' == ''">$(AVALONIA_LICENSE_KEY)</_AvaloniaLicenseKey>
	</PropertyGroup>
	<ItemGroup Condition="'$(_AvaloniaLicenseKey)' != ''">
		<AvaloniaUILicenseKey Include="$(_AvaloniaLicenseKey)" />
	</ItemGroup>
</Project>