<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Title>ImageMagitek</Title>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<RepositoryUrl>https://github.com/stevemonaco/ImageMagitek</RepositoryUrl>
	<PackageProjectUrl>https://github.com/stevemonaco/ImageMagitek</PackageProjectUrl>
	<IsTrimmable>true</IsTrimmable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ColorMinePortable" />
    <PackageReference Include="CommunityToolkit.Diagnostics" />
    <PackageReference Include="Monaco.PathTree" />
    <PackageReference Include="OneOf" />
    <PackageReference Include="SixLabors.ImageSharp" />
  </ItemGroup>

  <ItemGroup>
    <None Update="_codecs\*.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="_layouts\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="_palettes\DefaultNes.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="_palettes\DefaultRgba32.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="_schemas\CodecSchema.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="_schemas\GameDescriptorSchema.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="_schemas\ProjectSchema.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="_schemas\ResourceSchema.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="_xmlProjectSamples\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
