<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Semi.Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ImageMagitek\ImageMagitek.csproj" />
    <ProjectReference Include="..\ImageMagitek.PluginSamples\ImageMagitek.PluginSamples.csproj" />
  </ItemGroup>

</Project>
